export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILURE = "REGISTER_FAILURE"
//////////////////// FOR LOGIN /////////////
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"
//////////////////// FOR DILIVERY ADDRESS /////////
export const PAYMENT_REQUEST = "PAYMENT_REQUEST"
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS"
export const PAYMENT_FAILURE = "PAYMENT_FAILURE"